---

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  DisabledByDefault: true

  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0

  Exclude:
    - vendor/bundle/**/*

  DisplayCopNames: true

  StyleGuideCopsOnly: false

Metrics:
  Enabled: false

FactoryBot/AttributeDefinedStatically:
  Enabled: true
